"""Find duplicate publications and write src/data/publication-removals.json (entries hidden on the site).

Same work = near-identical title (ratio >= 0.85 after normalising) AND same first-author surname.
Rules: preprint vs published -> drop the preprint; same category -> keep the entry with a DOI / later year /
cleaner title. Journal vs conference versions are distinct publications and are both kept.
Nothing is deleted from publications*.json; removals are listed with the entry they duplicate.
"""
import json, re, difflib
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]; D = ROOT / "src/data"
A = json.loads((D / "publications.json").read_text()); B = json.loads((D / "publications-added.json").read_text())
items = [dict(p, _key=f"archived:{i}") for i, p in enumerate(A)] + [dict(p, _key=f"added:{i}") for i, p in enumerate(B)]
norm = lambda t: re.sub(r"[^a-z0-9 ]", "", re.sub(r"\s+", " ", (t or "").lower())).strip()
def first_surname(p):
    a = re.split(r"\s+and\s+|,\s*", p.get("authors") or "")[0].strip()
    return a.split()[-1].lower() if a else ""
def venue_key(p):
    v = re.sub(r"\(\d{4}\)", "", (p.get("venue") or "").lower()).replace("&", "and")
    v = re.sub(r"[^a-z ]", "", v).strip()
    return v[:25]
def quality(p):
    junk = bool(re.search(r"\.\s*(Sci Rep|Nature|IEEE)\b.*\d+:", p["title"]) or p["title"].lower().startswith("for presentation"))  # citation tail / note glued on
    return (0 if junk else 1, {"journals": 2, "conferences": 1}.get(p["category"], 0), 1 if p.get("doi") else 0, p.get("year") or 0, p["_key"].startswith("archived"))

removals, seen = [], set()
for i in range(len(items)):
    for j in range(i + 1, len(items)):
        a, b = items[i], items[j]
        if a["_key"] in seen or b["_key"] in seen: continue
        ta, tb = norm(a["title"]), norm(b["title"])
        r = difflib.SequenceMatcher(None, ta, tb).ratio()
        contained = min(len(ta), len(tb)) > 40 and (ta[:60] in tb or tb[:60] in ta)  # e.g. "For presentation in CDC '10 <title>"
        if not contained and (r < 0.85 or first_surname(a) != first_surname(b)): continue
        cats = {a["category"], b["category"]}
        if cats == {"journals", "conferences"}: continue  # distinct publications
        va, vb = venue_key(a), venue_key(b)
        if "preprints" not in cats and va and vb and va != vb: continue   # e.g. ACC paper vs journal paper
        da, db = (a.get("doi") or "").lower(), (b.get("doi") or "").lower()
        if da and db and da != db and "preprints" not in cats - {a["category"]} and a["category"] == b["category"] == "preprints": continue  # distinct preprints
        keep, drop = (a, b) if quality(a) >= quality(b) else (b, a)
        reason = "preprint of a published paper" if "preprints" in cats and len(cats) == 2 else "duplicate entry"
        removals.append({"key": drop["_key"], "title": drop["title"], "category": drop["category"], "year": drop.get("year"),
                         "keptKey": keep["_key"], "keptTitle": keep["title"], "keptCategory": keep["category"],
                         "similarity": round(r, 3), "reason": reason})
        seen.add(drop["_key"])
manual = D / "publication-removals-manual.json"
if manual.exists():
    have = {r["key"] for r in removals}
    removals += [dict(r, title=next((x["title"] for x in items if x["_key"] == r["key"]), None)) for r in json.loads(manual.read_text())["removals"] if r["key"] not in have]
(D / "publication-removals.json").write_text(json.dumps({"_note": "Generated by migration/scripts/dedupe_pubs.py. Entries hidden from the Publications page as duplicates.", "removals": removals}, indent=1, ensure_ascii=False))
print(len(removals), "duplicates")
for x in removals: print(f"- [{x['reason']}] {x.get('category')}/{x.get('year')}: {(x.get('title') or '')[:70]!r}\n    kept {x.get('keptCategory')}: {(x.get('keptTitle') or '')[:70]!r} ({x.get('similarity')})")
